from groq import Groq
from unidecode import unidecode
import re


# refined from https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/tree/master
_BAD_WORDS = [
    "aborto",
    "anus",
    "bastardo",
    "bicha",
    "biscate",
    "bissexual",
    "boceta",
    "boob",
    "bosta",
    "braulio",
    "burro",
    "cabrao",
    "cacete",
    "cagar",
    "camisinha",
    "caralho",
    "chochota",
    "chupar",
    "clitoris",
    "cocaina",
    "coito",
    "colhoes",
    "comer",
    "cona",
    "consolo",
    "corno",
    "cu",
    "esporra",
    "fecal",
    "filho da puta",
    "foda",
    "foder",
    "fuder",
    "gozar",
    "grelho",
    "heroina",
    "heterosexual",
    "homoerotico",
    "homosexual",
    "lesbica",
    "lolita",
    "mama",
    "merda",
    "paneleiro",
    "pau",
    "peidar",
    "penis",
    "pinto",
    "porra",
    "puta",
    "sacanagem",
    "saco",
    "transar",
    "vadia",
    "vai-te foder",
    "vai tomar no cu",
    "veado",
    "vibrador",
    "xana",
    "xochota",
    "2g1c",
    "acrotomophilia",
    "anal",
    "anilingus",
    "anus",
    "apeshit",
    "arsehole",
    "ass",
    "asshole",
    "assmunch",
    "babeland",
    "baby batter",
    "baby juice",
    "bastinado",
    "bbw",
    "bdsm",
    "beaner",
    "beaver cleaver",
    "beaver lips",
    "beastiality",
    "bestiality",
    "big breasts",
    "bimbos",
    "birdlock",
    "bitch",
    "bitches",
    "blowjob",
    "bollocks",
    "bondage",
    "boner",
    "boobs",
    "booty call",
    "bukkake",
    "bulldyke",
    "bullet vibe",
    "bullshit",
    "bunghole",
    "busty",
    "butt",
    "camel toe",
    "camgirl",
    "camslut",
    "camwhore",
    "carpet muncher",
    "cialis",
    "circlejerk",
    "clit",
    "clitoris",
    "clusterfuck",
    "cock",
    "cocks",
    "coprolagnia",
    "coprophilia",
    "cornhole",
    "coon",
    "creampie",
    "cum",
    "cumming",
    "cumshot",
    "cunnilingus",
    "cunt",
    "darkie",
    "deepthroat",
    "dendrophilia",
    "dick",
    "dildo",
    "dirty sanchez",
    "doggie style",
    "doggystyle",
    "dolcett",
    "domination",
    "dominatrix",
    "donkey punch",
    "double dong",
    "dry hump",
    "dvda",
    "ecchi",
    "ejaculation",
    "erotism",
    "escort",
    "eunuch",
    "fag",
    "faggot",
    "felch",
    "fellatio",
    "feltch",
    "femdom",
    "figging",
    "fingerbang",
    "fisting",
    "foot fetish",
    "footjob",
    "fuck",
    "fuckin",
    "fucking",
    "fudgepacker",
    "futanari",
    "gangbang",
    "genitals",
    "giant cock",
    "girl on girl",
    "goatse",
    "gokkun",
    "golden shower",
    "goregasm",
    "grope",
    "group sex",
    "g-spot",
    "guro",
    "handjob",
    "hardcore",
    "hentai",
    "hooker",
    "horny",
    "hot carl",
    "humping",
    "incest",
    "intercourse",
    "jack off",
    "jailbait",
    "jerk off",
    "jiggaboo",
    "jizz",
    "juggs",
    "kike",
    "kinbaku",
    "kinkster",
    "knobbing",
    "livesex",
    "lolita",
    "lovemaking",
    "masturbate",
    "milf",
    "missionary position",
    "motherfucker",
    "muffdiving",
    "nambla",
    "nawashi",
    "negro",
    "neonazi",
    "nigga",
    "nigger",
    "nimphomania",
    "nipple",
    "nsfw",
    "nudity",
    "nympho",
    "nymphomania",
    "octopussy",
    "omorashi",
    "one guy one jar",
    "orgasm",
    "orgy",
    "paedophile",
    "panties",
    "pedobear",
    "pedophile",
    "pegging",
    "penis",
    "phone sex",
    "pissing",
    "playboy",
    "pole smoker",
    "ponyplay",
    "poopchute",
    "porn",
    "porno",
    "pornography",
    "pthc",
    "pubes",
    "pussy",
    "queaf",
    "queef",
    "quim",
    "raghead",
    "rape",
    "raping",
    "rapist",
    "rectum",
    "rimjob",
    "rimming",
    "rosy palm",
    "rusty trombone",
    "sadism",
    "santorum",
    "scat",
    "schlong",
    "scissoring",
    "semen",
    "sexcam",
    "shaved beaver",
    "shaved pussy",
    "shemale",
    "shibari",
    "shit",
    "shitblimp",
    "shitty",
    "shota",
    "skeet",
    "slut",
    "s&m",
    "smut",
    "snatch",
    "snowballing",
    "sodomize",
    "sodomy",
    "splooge",
    "spooge",
    "spunk",
    "strapon",
    "strappado",
    "strip club",
    "suck",
    "sultry women",
    "swastika",
    "swinger",
    "taste my",
    "threesome",
    "thumbzilla",
    "tied up",
    "tit",
    "tits",
    "titties",
    "titty",
    "towelhead",
    "tranny",
    "tribadism",
    "tushy",
    "twat",
    "twink",
    "twinkie",
    "upskirt",
    "urethra play",
    "urophilia",
    "vagina",
    "viagra",
    "vibrator",
    "voyeur",
    "voyuer",
    "vulva",
    "wank",
    "wetback",
    "wet dream",
    "whore",
    "wrinkled starfish",
    "yaoi",
    "yellow showers",
    "yiffy",
    "zoophilia",
]


def get_is_safe_llamaguard_response(client: Groq, user_message: str) -> bool:
    pattern = r"\b(" + "|".join(re.escape(word) for word in _BAD_WORDS) + r")\b"
    if re.search(pattern, user_message, re.IGNORECASE):
        return False
    chat_completion = client.chat.completions.create(
        messages=[{"role": "user", "content": user_message}],
        model="llama-guard-3-8b",
    )
    return chat_completion.choices[0].message.content.startswith("safe")


# get_is_safe_llamaguard_response(client, "curently")


# Exemplo de uso :D
# get_is_safe_llamaguard_response(client, "curently")
# >>> True
# get_is_safe_llamaguard_response(client, "vai se tomar nu cu")
# >>> False
